name: Validate data.json on PR

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable corepack
        run: corepack enable

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Validate data.json
        run: yarn run validate


